#!/bin/sh

AUTORECONF=${AUTORECONF:-autoreconf}
CVS=${CVS:-cvs}
MAKE=${MAKE:-make}
PATCH=${PATCH:-patch}
SD=$(cd $(dirname $0) && echo ${PWD})

if ! test -d ${WD}
then
    mkdir -p ${WD} && cd ${WD} \
        || exit $?
fi

# Create autoconf files
if ! test -x ${SD}/configure
then
    cd ${SD} && ${AUTORECONF} --verbose --install --symlink \
        || exit $?
fi

# Configure OpenPACE
if ! test -r ${SD}/Makefile
then
	${SD}/configure \
        || exit $?
fi

# Build OpenPACE
if ! test -x ${WD}/src/eactest
then
    ${MAKE} -C ${WD} \
        || exit $?
fi

${WD}/src/eactest \
    || exit $?
