#!/bin/sh

AUTORECONF=autoreconf
CVS=cvs
MAKE=make
PATCH=patch
WD=`pwd`
OPENSSL_DIR=${WD}/openssl

# Fetch OpenSSL
if ! test -d ${OPENSSL_DIR}
then
	${CVS} -d anonymous@cvs.openssl.org:/openssl-cvs co `basename ${OPENSSL_DIR}` \
        || exit $?
fi

# Configure OpenSSL (and create ${OPENSSL_DIR}/include/openssl/obj_mac.h)
if ! test -r ${OPENSSL_DIR}/Makefile
then
	cd ${OPENSSL_DIR} \
        && ./config -fPIC shared \
        || exit $?
    cd ${WD}
fi

# Patch OpenSSL with OpenPACE object identifiers
if ! grep NID_id_PACE_ECDH_GM_AES_CBC_CMAC_256 ${OPENSSL_DIR}/include/openssl/obj_mac.h > /dev/null
then
	${PATCH} --directory=${OPENSSL_DIR} -p1 < oids.patch \
        || exit $?
fi

# Build OpenSSL
if ! test -r ${OPENSSL_DIR}/libcrypto.a
then
	${MAKE} -C ${OPENSSL_DIR} \
        || exit $?
    echo "Built OpenSSL with OpenPACE object identifiers"
    echo ""
fi

# Create autoconf files
if ! test -x configure
then
    ${AUTORECONF} --verbose --install --symlink \
        || exit $?
fi

# Configure OpenPACE
if ! test -r Makefile
then
	./configure \
        CRYPTO_CFLAGS=-I${OPENSSL_DIR}/include \
        CRYPTO_LIBS="${OPENSSL_DIR}/libcrypto.a -ldl" \
        || exit $?
fi

# Build OpenPACE
if ! test -x src/eactest
then
    ${MAKE} \
        || exit $?
    echo "Built OpenPACE"
    echo ""
fi

src/eactest \
    || exit $?
