#!/bin/bash

for f in \
	/Library/OpenPACE/bin/cvc* \
	/Library/OpenPACE/lib/python2.7/site-packages/* \
	/Library/OpenPACE/share/doc/openpace \
	/Library/OpenPACE/share/man/man1/*
do
	a=/Library/OpenPACE
	b=/usr/local
	l="$(dirname ${f/$a/$b})"
	mkdir -p $l
	ln -sf $f $l
done
