#!/bin/bash

# Remove symlinks to commands
for file in /Library/OpenPACE/bin/*; do
	test -L "/usr/local/bin/$(basename $file)" && rm -f "/usr/local/bin/$(basename $file)"
done

# Remove installed files
rm -rf /Library/OpenPACE

echo "OpenPACE has been removed from your system. See you again!"
