#!/bin/bash

set -ex

for f in \
	/Library/OpenPACE/bin/cvc* \
	/Library/OpenPACE/lib/python2.7/site-packages/* \
	/Library/OpenPACE/share/doc/openpace \
	/Library/OpenPACE/share/man/man1/*
do
	a=/Library/OpenPACE
	b=/usr/local
	l="${f/$a/$b}"
	test -L "$l" && rm -f "$l"
done

# Remove installed files
rm -rf /Library/OpenPACE

echo "OpenPACE has been removed from your system. See you again!"
